name: Backend CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest
    environment: Production Env
    defaults:
      run:
        shell: bash
        working-directory: ./starter/backend

    steps:
    - name: Start setup Repository
      uses: actions/checkout@v3

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Setup Python Dependencies
      run:  |
        python -m pip install --upgrade pip
        pip install pipenv
        pip install flake8

    - name: Run Lint
      run: pipenv run lint

  Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./starter/backend

    steps:
    - name: Start setup Repository
      uses: actions/checkout@v3

    - name: Setup Python 3.10
      uses:  actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Setup Python Dependencies
      run:  |
        python -m pip install --upgrade pip
        pip install pipenv
        pip install flake8

    - name: Install Pytest
      run: pipenv install pytest && pipenv run test
      
    - name: Run Test
      run: pipenv run test

      
  Build:
    needs: [Lint, Test]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./starter/backend
    
    steps:
    - name: Setup the Repository
      uses: actions/checkout@v3

    - name: Build Image
      run: docker build --tag mp-backend:latest .


